name : ci-demo
on : push
jobs :
  build_and_deploy :
   runs-on : ubuntu-latest
   steps: 
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: maven compile
      run: mvn compile
    - name : Build
      run : mvn clean install
