name: Snyk Scan

on:
  push:
    branches:
      - master

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Snyk Authentication
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Scan
      run: snyk test --json > snyk-report.json

    - name: Display Snyk Scan Results
      run: cat snyk-report.json

    - name: Upload Snyk Results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-report.json
